name: spark-stack
services:
  spark-master:
    build:
      context: /home/admin/spark-custom
      dockerfile: Dockerfile
    container_name: spark-master
    environment:
      SPARK_MODE: master
      SPARK_MASTER_HOST: ${SPARK_MASTER_HOST}
      SPARK_MASTER_WEBUI_PORT: ${SPARK_MASTER_WEBUI_PORT}
      JUPYTER_MODE: master
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
    volumes:
      - /home/admin/spark-custom/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
      - /home/admin/spark-custom/jupyter_server_config.py:/root/.jupyter/jupyter_server_config.py
      - /mnt/nfs/dockers/jupyter:/home/iceberg/notebooks
    # ports:
    #   - "7077:7077"
    #   - "8081:8081" # Master UI
    #   - "8888:8888" # Jupyter UI
    #   - "4040:4040" # Driver port (set with spark.driver.port)
    #   - "7079:7079" # (Optional) Block manager port
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 3G

  spark-worker:
    build:
      context: /home/admin/spark-custom
      dockerfile: Dockerfile
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: ${SPARK_MASTER_URL}
      SPARK_LOCAL_IP: ${SPARK_LOCAL_IP}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
    volumes:
      - /home/admin/spark/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
    network_mode: host
    depends_on:
      - spark-master
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: "2"
          memory: 4G