name: iceberg-catalog-stack
services:
  iceberg-rest:
    # https://hub.docker.com/r/tabulario/iceberg-rest
    # Ref: https://iceberg.apache.org/spark-quickstart/#docker-compose 
    image: tabulario/iceberg-rest:latest@sha256:3b7d31bdfec626b68e97531c9778a1b9119659e456fe28545a49f6aa6a9ce472
    container_name: iceberg-rest
    restart: unless-stopped
    ports:
      - "8181:8181"  # Expose REST Catalog on port 8181
    environment:
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      AWS_REGION: ${AWS_REGION}
      CATALOG_NAME: ${ICEBERG_CATALOG_NAME}
      CATALOG_WAREHOUSE: ${ICEBERG_WAREHOUSE}
      CATALOG_IO__IMPL: org.apache.iceberg.aws.s3.S3FileIO
      CATALOG_S3_ENDPOINT: ${MINIO_ENDPOINT}
      CATALOG_CATALOG__IMPL: org.apache.iceberg.jdbc.JdbcCatalog
      CATALOG_URI: jdbc:postgresql://${POSTGRESS_HOSTNAME}:${POSTGRESS_HOSTNAME_PORT}/${PSQL_ICEBERG_DB}
      CATALOG_JDBC_USER: ${PSQL_ICEBERG_USER}
      CATALOG_JDBC_PASSWORD: ${PSQL_ICEBERG_PASSWORD}
    # Synology Container Manager uses as default log.db, however, due my fluentbit flow
    # I am reading logs from json files, flagging it here in the compose to force Synlogy 
    # to save logs the way I need them.
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

